<a href="https://colab.research.google.com/github/jack02061987/curso_ebac_frontend/blob/exercicio_git/Conhe%C3%A7a_o_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd

In [30]:
df = pd.read_csv('/content/cadastro_clientes.csv')

In [31]:
df.head()

,ID_Cliente,Nome,Idade,Sexo,Cidade,Estado,Data_Cadastro,Gasto_Total
0,1,Esther Lima,61,Masculino,da Rocha,PR,2024-08-31,7466.98
1,2,Bryan Araújo,27,Feminino,Alves,PR,2024-11-01,5495.21
2,3,Laís Mendes,28,Masculino,Melo,ES,2025-03-04,4127.34
3,4,Srta. Ana Clara Lima,34,Feminino,Castro,RN,2024-10-19,7245.87
4,5,Esther Pereira,26,Masculino,Sales,PI,2023-07-17,9976.92

In [36]:
df[df["Sexo"] == "Masculino"]

,ID_Cliente,Nome,Idade,Sexo,Cidade,Estado,Data_Cadastro,Gasto_Total
0,1,Esther Lima,61,Masculino,da Rocha,PR,2024-08-31,7466.98
2,3,Laís Mendes,28,Masculino,Melo,ES,2025-03-04,4127.34
4,5,Esther Pereira,26,Masculino,Sales,PI,2023-07-17,9976.92
7,8,Sr. João Felipe Monteiro,52,Masculino,Barros de Mendes,SE,2023-07-07,5342.52
8,9,Eduardo Freitas,53,Masculino,Porto Alegre,CE,2024-03-10,4400.47
11,12,Ana Julia Viana,62,Masculino,Cardoso,TO,2023-11-25,4779.47
12,13,Bernardo Duarte,68,Masculino,da Rosa da Serra,PR,2023-08-02,6795.62
13,14,Vitor Hugo da Costa,48,Masculino,Oliveira,SE,2023-05-21,2443.25
14,15,Leandro Castro,28,Masculino,Rocha das Flores,AP,2023-09-22,8760.77
15,16,Alexandre Silva,27,Masculino,Lopes de Gonçalves,RR,2023-09-05,5906.18
16,17,Sarah Cavalcanti,36,Masculino,Rodrigues Alegre,RR,2024-07-24,6831.84
17,18,Eduarda da Costa,58,Masculino,Almeida da Serra,RN,2025-01-22,3425.30

In [37]:
df_masculino = df[df["Sexo"] == "Masculino"]

In [38]:
df_masculino.head(20)

,ID_Cliente,Nome,Idade,Sexo,Cidade,Estado,Data_Cadastro,Gasto_Total
0,1,Esther Lima,61,Masculino,da Rocha,PR,2024-08-31,7466.98
2,3,Laís Mendes,28,Masculino,Melo,ES,2025-03-04,4127.34
4,5,Esther Pereira,26,Masculino,Sales,PI,2023-07-17,9976.92
7,8,Sr. João Felipe Monteiro,52,Masculino,Barros de Mendes,SE,2023-07-07,5342.52
8,9,Eduardo Freitas,53,Masculino,Porto Alegre,CE,2024-03-10,4400.47
11,12,Ana Julia Viana,62,Masculino,Cardoso,TO,2023-11-25,4779.47
12,13,Bernardo Duarte,68,Masculino,da Rosa da Serra,PR,2023-08-02,6795.62
13,14,Vitor Hugo da Costa,48,Masculino,Oliveira,SE,2023-05-21,2443.25
14,15,Leandro Castro,28,Masculino,Rocha das Flores,AP,2023-09-22,8760.77
15,16,Alexandre Silva,27,Masculino,Lopes de Gonçalves,RR,2023-09-05,5906.18
16,17,Sarah Cavalcanti,36,Masculino,Rodrigues Alegre,RR,2024-07-24,6831.84
17,18,Eduarda da Costa,58,Masculino,Almeida da Serra,RN,2025-01-22,3425.30

In [39]:
# filtrando mais de um valor

df[df["Estado"].isin(["RR", "TO", "PR"])]

,ID_Cliente,Nome,Idade,Sexo,Cidade,Estado,Data_Cadastro,Gasto_Total
0,1,Esther Lima,61,Masculino,da Rocha,PR,2024-08-31,7466.98
1,2,Bryan Araújo,27,Feminino,Alves,PR,2024-11-01,5495.21
11,12,Ana Julia Viana,62,Masculino,Cardoso,TO,2023-11-25,4779.47
12,13,Bernardo Duarte,68,Masculino,da Rosa da Serra,PR,2023-08-02,6795.62
15,16,Alexandre Silva,27,Masculino,Lopes de Gonçalves,RR,2023-09-05,5906.18
16,17,Sarah Cavalcanti,36,Masculino,Rodrigues Alegre,RR,2024-07-24,6831.84